services:
  thechristiancrew.globalthemeinc.listener:
    class: thechristiancrew\globalthemeinc\event\main_listener
    arguments:
      - @template
      - %core.root_path%
    tags:
      - { name: event.listener }
